version: "2.1"

executors:
  my-node:
    docker:
      - image: circleci/node:12.2

orb:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  test-code:
    executor: my-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pathfinding-visualizer-{{ checksum "./package-lock.json" }}
            - v1-pathfinding-visualizer
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Executing tests
          command: |
            npm run test
      - save_cache:
          when: on_success
          key: v1-pathfinding-visualizer-{{ checksum "./package-lock.json" }}
          paths:
            - ./node_modules
  
  deploy-code:
    executor: my-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pathfinding-visualizer-{{ checksum "./package-lock.json" }}
            - v1-pathfinding-visualizer
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Building
          command: |
            npm run build

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test-code
      - deploy-code:
          requires:
            - test-code
          context: AWS
