version: "2.1"

executors:
  my-node:
    docker:
      - image: circleci/node:12.2

orbs:
  aws-s3: circleci/aws-s3@1.0.15

jobs:
  test-code:
    executor: my-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pathfinding-visualizer-{{ checksum "./package-lock.json" }}
            - v1-pathfinding-visualizer
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Executing tests
          command: |
            npm run test
      - save_cache:
          when: on_success
          key: v1-pathfinding-visualizer-{{ checksum "./package-lock.json" }}
          paths:
            - ./node_modules
  
  deploy-code:
    executor: my-node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pathfinding-visualizer-{{ checksum "./package-lock.json" }}
            - v1-pathfinding-visualizer
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Building
          command: |
            npm run build
      - aws-s3/sync:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          arguments: |
            --acl public-read
          from: ./dist
          to: $S3_URL
          overwrite: true

workflows:
  version: 2
  test-and-deploy:
    jobs:
      # - test-code
      - deploy-code:
          requires:
            - test-code
          context: AWS
